### ISSUE TITLE
What fonts are required?

### ISSUE THREAD

**Issue by isaiahtaylor** [nicomazz/i3-polybar-config#2]
Hello, thank you for your work on this! It was a great introduction for me to polybar. Could you list the fonts that this depends on? It is a little difficult to figure it out from the "Dropping unmatched character" messages. Thanks!

**Comment by nicomazz** [comment]
Hi! Thanks for having opened this issue. Unfortunately, I will not have my main laptop for a few days. I'll address this issue as soon as possible! (:

**Comment by nicomazz** [comment]
Sorry for the late reply.
Regarding the fonts, [this link](https://github.com/polybar/polybar/wiki/Fonts#freetype-fonts) will surely help to troubleshoot your problem.

I think that the fonts needed are the following:
FontAwesome 
Material icons
Nerd Patched Fonts 
[Siji](https://github.com/stark/siji)

If you find that something is missing after having installed the previous fonts, let me know!
